
# rooms to have the bot connect to
roomEndpoints:
  - "wss://euphoria.io/room/testing/ws"
  - "wss://euphoria.io/room/bots/ws"

# Color minecraft usernames in minecraft chat
coloredMinecraftNames: true

# Color euphoria names in minecraft chat
coloredEuphNames: true

# if true, closes bridges early after bridgeInactivityPeriod seconds of inactivity from any bridge
bridgeInactivityCheck: true #UNIMPLEMENTED

bridgeInactivityPeriod: 600

# how long in seconds to wait before closing a bridge regardless of activity
# -1 disables auto-closing
maximumBridgeLife: 180



# settings for threaded chat
threadedChat:

  # attempts to recreate euphoria style threading in minecraft (will bridge across minecraft and rooms)
  enabled: false

  # text to indent indented messages with
  indentationText: "   "

  # coloredMinecraftNames and coloredEuphNames no longer work because the threading system cant differentate between minecraft and euphoria messages, so coloring names depends on coloredMinecraftNames

  # sets how many threaded messages to keep in memory until we start removing the old ones
  # only does anything when threadedChat is true obviously
  messageLimit: 1000

  # how long to keep normal chat on the player's chat before disappearing
  # in seconds
  normalChatLife: 10

