  name: EuphBridgeBot
  main: io.github.kidofcubes.Main
  version: 0.1
  author: KidOfCubes
  commands:
    setcursor:
      description: Moves your cursor to under the message with the specified snowflake
      usage: /<command> (snowflake)